### ISSUE TITLE
Panic when the `consul-alerts/reminders/` is empty

### ISSUE THREAD

**Issue by moadqassem** [AcalephStorage/consul-alerts#248]
**Go version:** _go.11.1_
**OS:** _MacOS Mojave_
**Consul Version:** _1.4.2_
**Consul-Alerts Version:** _0.5.0_

**Description:** 

When a user creates manually an empty reminder folder (e.g: `consul-alerts/reminders/` ), the consul-alerts binary simply panics and that panic doesn't recover which would kill the watching process. 

The reason for the panic is, there is no check to see if the reminders folder has some subfolders or not. 

```shell
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).UpdateCheckData(0xc420290000)
	/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:306 +0xe98
github.com/AcalephStorage/consul-alerts/consul.NewClient(0xc4200cc30e, 0xe, 0xc4200cc3fd, 0x3, 0xc42002653c, 0x2, 0x1b, 0xc420143c88, 0x40d0e5)
	/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:63 +0x28f
main.daemonMode(0xc4201c0e10)
	/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:144 +0x66e
main.main()
	/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:58 +0xf4
```

**Comment by moadqassem** [comment]
I have actually solved the problem and its in a branch, but I am not able to push the branch to the remote repo due some lack of permissions.

**Comment by moadqassem** [comment]
Here is the PR which solves the issue: https://github.com/AcalephStorage/consul-alerts/pull/250
