### ISSUE TITLE
Consul-alerts crashes if Consul dies

### ISSUE THREAD

**Issue by vidarh** [AcalephStorage/consul-alerts#34]
Rather than triggering an alert, when killing Consul while consul-alerts is running in a Docker container just built based on the golang Docker container, and using "go get ...", I get this:

Prior to taking down Consul:

```
time="2015-01-27T17:07:30Z" level="info" msg="Checking consul agent connection..."
time="2015-01-27T17:07:30Z" level="info" msg="Consul Alerts daemon started"
time="2015-01-27T17:07:30Z" level="info" msg="Consul Alerts Host: 1dab0b580258"
time="2015-01-27T17:07:30Z" level="info" msg="Consul Agent: 192.168.0.44:8500"
time="2015-01-27T17:07:30Z" level="info" msg="Consul Datacenter: dc1"
time="2015-01-27T17:07:50Z" level=warning msg="Unable to retrieve node name." 
```

Consul gets killed here. Few seconds later:

```
panic: interface conversion: interface is nil, not string

goroutine 11 [running]:
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).retrieveNode(0xc20802e960)
        /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:141 +0x257
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc20802e960)
        /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:99 +0x36
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc20802e960)
        /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
created by github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).RunForElection
        /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:46 +0x32

goroutine 1 [chan receive]:
main.daemonMode(0xc2080c3c80)
        /go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:110 +0x111e
main.main()
        /go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:49 +0x13c

goroutine 5 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 12 [chan receive]:
main.processEvents()
        /go/src/github.com/AcalephStorage/consul-alerts/event-handler.go:42 +0x72
created by main.daemonMode
        /go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:99 +0xe8f

goroutine 13 [chan receive]:
main.processChecks()
        /go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:51 +0x47
created by main.daemonMode
        /go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:100 +0xea0

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0xc2080bfc60, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080bfc60, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080bfc00, 0x0, 0x7f4682481d30, 0xc2080c7088)
        /usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c1b0, 0x48c824, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20802c1b0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208054de0, 0x7f46824838b0, 0xc20802c1b0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208054de0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0x7fff18f9eed8, 0xc, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1808 +0xba
created by main.daemonMode
        /go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:106 +0xf76
```

**Comment by vidarh** [comment]
This looks to be a failure of error checking in consul-skipper (retrieveNode in skipper.go sets c.node to nil in the case of a failure). I'll prepare a patch.

However even with fixing this, it seems consul going away does not trigger a notification, but I'll look into that more closely.

**Comment by vidarh** [comment]
I've submitted a pull request to consul-skipper to fix this upstream:
https://github.com/darkcrux/consul-skipper/pull/1

**Comment by darkcrux** [comment]
Cool. Thank @vidarh, I'll have a look at it.

**Comment by fusiondog** [comment]
Looks like the upstream pull request was merged.  Current behaviour on consul failing is for consul-alerts to close but it doesn't seem to crash the same way.  I think that closing is probably the correct step as it is dependent.  Closing pending further concern.
